name: flutterfiretest
description: A new Flutter project, designed to help users learn and memorize information using flashcards.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^2.2.1
  supabase_flutter: ^2.0.0
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  curved_navigation_bar: ^1.0.6
  flutter_slidable: ^4.0.0
  flutter_lints: ^2.0.0
  flutter_card_swiper: ^7.0.2
  email_validator: ^3.0.0
  fl_chart: ^0.69.0
  animated_splash_screen: ^1.3.0
  eva_icons_flutter: ^3.1.0
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  cron: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  assets:
    - assets/brain-openmoji.png
